### PR TITLE
PHP Struct: test that it's PHP 8 compatible

### PR DESCRIPTION
**Pull request by davidrans**
This also updates PHPUnit, and fixes a couple things to get Travis and Code Climate happy again.

This doesn't make any functional changes, so I don't think this needs QA.

qa_req 0

### CODE REVIEW

**Comment by BaseInfinity** [comment]
kewlll, CR 👙

**Comment by BaseInfinity** [comment]
CR 👙  weird the previous one didnt stick

**Comment by sterlinghirsh** [comment]
CR :zap: Maybe we should have called it php8-struct

**Comment by davidrans** [comment]
I was gonna change the repo name, but then decided not to jump through all the hoops with composer, travis, code climate, ...

**Pull request merged**
