### PR TITLE
Use Psalm for static analysis

### PR DESCRIPTION
**Pull request by davidrans**
This adds Psalm to CI for this repo, and also adds some types it asked for.

qa_req 0 (Since this only changes types and is thoroughly covered by tests)

### CODE REVIEW

**Comment by davidrans** [comment]
deploy_block :hand: on #5 which this is based on

**Comment by BaseInfinity** [comment]
Cool! CR 👙

**Comment by davidrans** [comment]
dev_block :hand:
This makes the constructor final, but we have some subclasses that extend it in our repo. That means that `amend()` might not work if those constructors change the signature, which is what psalm was warning about here.

**Comment by davidrans** [comment]
Here's a failing test:
```
diff --git tests/StructTest.php tests/StructTest.php                      
index 5193cff..824edef 100644                                             
--- tests/StructTest.php                                                  
+++ tests/StructTest.php                                                  
@@ -133,6 +133,12 @@ class StructTest extends PHPUnit\Framework\TestCase {
       $this->assertSame(4, $amended->a);                                 
       $this->assertSame(2, $amended->b);                                 
    }                                                                     
+                                                                         
+   public function testAmendConstructorOverride() {                      
+      $struct = new TypedStruct(1, 'asdf');                              
+      // Throws exception                                                
+      $struct->amend(['integer' => 2]);                                  
+   }                                                                     
 }                                                                        
                                                                          
 class MyStruct extends Struct {                                          
@@ -146,3 +152,14 @@ class YourStruct extends Struct {                    
 class ChildStruct extends MyStruct {                                     
    protected const FIELDS = ['c'];                                       
 }                                                                        
+                                                                         
+class TypedStruct extends Struct {                                       
+   protected const FIELDS = ['integer', 'string'];                       
+                                                                         
+   public function __construct(int $integer, string $string) {           
+      return parent::__construct([                                       
+         'integer' => $integer,                                          
+         'string' => $string,                                            
+      ]);                                                                
+   }                                                                     
+}                                                                        
```

I'm gonna remove the `amend()` feature cause we're not using it in our repo, and it's bugged if subclasses override the constructor (which they do, in our repo).

Thanks psalm!

**Comment by davidrans** [comment]
un_dev_block :+1:

**Comment by andyg0808** [comment]
CR :fish: through 882d819

**Pull request merged**
